# -*- coding: utf-8 -*-
"""lấy văn bản trong url.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12SJg6YSe1cYgBgNL1SkZ477Cpc6cUWxB
"""

import requests
from bs4 import BeautifulSoup

def extract_text_from_url(url):
    try:
        # Thêm headers để giả lập trình duyệt
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }

        # Gửi request với headers
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        # Tạo đối tượng BeautifulSoup
        soup = BeautifulSoup(response.text, 'html.parser')

        # Loại bỏ các thẻ script và style
        for script in soup(["script", "style"]):
            script.decompose()

        # Lấy text và giữ nguyên xuống dòng
        text = soup.get_text(separator='\n')

        # Xử lý text: loại bỏ khoảng trắng thừa nhưng giữ xuống dòng
        lines = [line.strip() for line in text.splitlines()]
        text = '\n'.join(line for line in lines if line)

        return text

    except Exception as e:
        return f"Có lỗi xảy ra: {str(e)}"

# Sử dụng
url = "https://website.com/"
text = extract_text_from_url(url)
print(text)